# Site settings
title: William Meng
subtitle:
description: My personal site
baseurl: "/"
url: https://williammeng.com
enforce_ssl: williammeng.com
author: William Meng

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/wlmeng11
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/wlmeng11/
linkedin_url: https://www.linkedin.com/in/william-m-79687b102/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
