# Site settings
title: William Meng
subtitle:
email: youremailaddress@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/"
url: "wlmeng11.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/wlmeng11
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/wlmeng11/
linkedin_url: https://www.linkedin.com/in/william-m-79687b102/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
